FROM apache/airflow:2.10.5-python3.12

USER root
RUN python -m venv /opt/dbt \
    && /opt/dbt/bin/pip install --no-cache-dir --upgrade pip \
    && /opt/dbt/bin/pip install --no-cache-dir "dbt-core==1.11.14" "dbt-postgres==1.11.0" \
    && chown -R airflow:0 /opt/dbt
USER airflow
